Archive lines
LocalCrag/LocalCragApp pull request #480
Opened 2024-10-22 21:43 UTC by BlobbyBob

Implements

> Add "old" Property to lines and Topo images

from #341

Some info:
- everyone can access archived entities via the API, but only moderators see the show/hide archive buttons, so the UI does not get polluted for most people
- I'm not fully satisfied yet with the icon choice, but the icon set does not really offer that much which fits imo
- Most instances probably don't need an archive, so we could make this an instance setting (which it currently is not). Not sure, whether this would be good or not
- Crags/Sectors/Areas can be archived, which archives all contents, but this cannot be reverted (as this would likely restore more than the moderator would want)
- Todo entries are not touched, so if a line is unarchived the todo is restored. Only archived todos are hidden
- Ascents of archived lines are not hidden

2024-10-23 16:22 UTC, dorthrithil commented on client/src/app/models/sector.ts
>    mapMarkers: MapMarker[];
deserialize missing archived attribute

2024-10-23 16:32 UTC, dorthrithil commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
I would prefer having separate endpoints for the archive actions, smth like `/lines/bleausard/set-archived`. All the other entity data will never change in those requests.

2024-10-23 20:56 UTC, BlobbyBob commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
I thought about it too and my first draft was like that. But then I thought that (especially on lines an topo images) this is just a simple property without side effect, so why introduce another endpoint instead of re-using an existing one.

I think for `sector`, `area` and `crag` the argument for a new endpoint makes more sense as it is not a property on those objects.

2024-10-24 05:54 UTC, dorthrithil commented
I think I will create a feature branch for the gym mode in which this and coming gym features can be merged until we have an MVP with everything you need to run LC in a gym. This way you wouldn't need to do stuff like the gym mode setting flag right away and can work more incrementally.
If this is fine for you, I'll do that after 1.7.2 is finished hopefully this weekend.

2024-10-24 06:20 UTC, dorthrithil commented on client/src/app/models/crag.ts
> +  archived?: boolean;
Ah, didn't notice it is not a property of a crag when I wrote this. :D

2024-10-24 06:23 UTC, dorthrithil commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
What about a different approach then, smth like:

`/archive?slug=bleausard&type=LINE`

Then we have a single endpoint handling all the archiving which can, depending on type, call the respective archiving functions.

2024-10-24 17:55 UTC, BlobbyBob commented
Yeah sounds fine. I just need to make sure it does not deviate too much from the main development line, but I guess regular merging should do it.

2024-10-24 18:01 UTC, BlobbyBob commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
This was basically my zero-th draft :D
I first thought it was fine, but then I saw no argument why setting `archived` to true on a line or topo image should be treated somewhat special compared to other properties like secret. Do you have an argument for that?

I'm fine with returning to that approach if I see a (semantical or architectural) advantage but currently I struggle to find any.

2024-10-25 18:15 UTC, dorthrithil commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
My lines of thought were, that having a dedicated archival endpoint is better SOC. Archiving a line has drastically different effects than setting any other property on a line. The line will be displayed in a separate part of the app and archived lines cannot be un-archived. This, plus the fact that we have more levels that can be archived, where the archive property doesn't exist on the model we are actually trying to update (sending archive=true is more like a side effect hack there). 

I think maintainabillty is also better with this approach, as all archive relevant code is at one place.

Additionally, in a hypothetical scenario, this single archive endpoint could be protected by permissions way more easier in the future than the current approach, by just using the decorator.

2024-10-25 18:30 UTC, BlobbyBob commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
Just FYI: In this PR it is possible to un-archive a line and a topo-image. The main use case for this is just to prevent misclicks having "fatal" consequences.
As there is quite some stuff connected to a line, recreating would be far from simple and cause a lot of nasty details.

2024-10-25 19:03 UTC, BlobbyBob commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
Do you think this un-archiving works better with `/lines/bleausard/set-archived` or with `/archive?slug=bleausard&type=LINE`?

2024-10-25 20:08 UTC, dorthrithil commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
> Just FYI: In this PR it is possible to un-archive a line and a topo-image. The main use case for this is just to prevent misclicks having "fatal" consequences. As there is quite some stuff connected to a line, recreating would be far from simple and cause a lot of nasty details.

Ahh, I've misread the part about non-revertability above in the description. This is just for areas/crags/sectors which makes sense.

Still my feeling is having a single endpoint is good SOC here. 

> Do you think this un-archiving works better with /lines/bleausard/set-archived or with /archive?slug=bleausard&type=LINE?

Probably the main difference is having 4 endpoints for `/lines/bleausard/set-archived` and only one for 
`/archive?slug=bleausard&type=LINE`.

2024-10-27 08:10 UTC, BlobbyBob commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +      this.linesService.updateLine(this.line).subscribe(resultHandler);
I've implemented the new endpoint and rolled back the other changes. 
So just another FYI: The `archived` property needs to stay on lines and topoImages as the frontend presents them differently. This means that we now have a new read-only property on those, which can, in fact, be written to, but only via another endpoint.

2024-10-27 08:14 UTC, BlobbyBob commented
> I think we should introduce an instance setting right away in this PR, smth like gym_mode_enabled

I've opened another PR for that, so they are still in a reviewable size for you. When #485 gets merged, I will add the missing directives into this one, and then it should be finally ready.

2024-10-27 11:11 UTC, dorthrithil requested changes

2024-10-27 11:11 UTC, dorthrithil commented on server/src/resources/archive_resources.py
> +            topo_image = TopoImage.query.filter(TopoImage.id == archive_data["slug"]).first()
`find_by_id` should work here and also do the None check
Maybe add a short comment why slug is actually an id here or send the id in the payload

2024-10-27 11:11 UTC, dorthrithil commented on server/src/resources/archive_resources.py
> +            topo_image = TopoImage.query.filter(TopoImage.id == archive_data["slug"]).first()
Maybe set all order props of archived topo images to None and then update existing order ids so that there are no missing numbers (after e.g. archiving the 2nd of 5 images). Would be nice to stay clean there, even if it probably works just like it is now. :)

2024-10-27 14:19 UTC, BlobbyBob commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +  @Input() style = "plain";
done

2024-10-27 14:19 UTC, BlobbyBob commented on client/src/app/modules/archive/archive-button/archive-button.component.ts
> +  switchArchived(event: MouseEvent) {
fine with me

2024-10-27 14:20 UTC, BlobbyBob commented on client/src/app/modules/line/line-list/line-list.component.ts
> +      const filters = new URLSearchParams();
Yeah, it's pretty nice as its simple, does all escaping for you and is contained in the standard library

2024-10-27 14:21 UTC, BlobbyBob commented on client/src/app/services/crud/archive.service.ts
> + * CRUD service for areas.
Yeah, copy pasting issues :D
I've left the jsdoc comments on the functions though, as they might not be directly 100% clear to everyone.

2024-10-27 14:21 UTC, BlobbyBob commented on client/src/app/services/crud/archive.service.ts
> +      .post(this.api.archive.setArchived(), {
done

2024-10-27 14:23 UTC, BlobbyBob commented on client/src/app/services/crud/archive.service.ts
> +  /**
I think the `ArchiveType` enum and whether to use a slug id, and whether only `true` or also `false` is allowed are details which are decently abstracted hidden from the normal code currently.

2024-10-27 14:24 UTC, BlobbyBob commented on server/src/migrations/versions/544c5d2ae547_added_old_property_to_lines_and_topo_.py
> +def upgrade():
Migrations are treated as atomic by default and there is no "official CLI" way to merge two. I've fixed it manually instead

2024-10-27 14:31 UTC, BlobbyBob commented on server/src/resources/archive_resources.py
> +            topo_image = TopoImage.query.filter(TopoImage.id == archive_data["slug"]).first()
> Maybe add a short comment why slug is actually an id here

done

> Maybe set all order props of archived topo images to None and then update existing order ids

I'm not a fan of this as un-archiving a topo image would require you to restore the order manually. In practice, it's very likely that restoring archived entities will only happen shortly after archiving and then nothing breaks and it's beneficial that the order stays untouched. Furthermore, every API call to reorder the topo images automatically fixed the indices to look "nice" again.

2024-10-27 19:30 UTC, dorthrithil commented on server/src/resources/archive_resources.py
> +            topo_image = TopoImage.query.filter(TopoImage.id == archive_data["slug"]).first()
Hm yeah, that's a point

2024-10-27 19:32 UTC, dorthrithil requested changes

2024-10-27 19:32 UTC, dorthrithil commented on server/src/resources/archive_resources.py
> +                raise NotFound()
`find_by_id` is already raising `NotFound`

2024-10-27 19:53 UTC, dorthrithil approved these changes

2024-10-27 19:54 UTC, merged