Gym Usage: Line Colors
LocalCrag/LocalCragApp pull request #487
Opened 2024-10-27 19:52 UTC by BlobbyBob

:sparkles: Lines have an optional color associated with them
:sparkles: Line Form allows setting the color if in gym mode and suggests 10 (currently hardcoded) colors
:sparkles: UI respects the line colors whereever set and falls back to the instance setting otherwise

2024-10-30 17:40 UTC, dorthrithil requested changes
- No color tests
- I think there is no option to set a color back to null (this is, making it take the default color, even if you change that)
- The archive controls should be gym mode only. Could be validated on backend too, but I think hiding it is enough as we are not exposing any sensitive api to non-moderators

2024-10-30 17:40 UTC, dorthrithil commented on client/src/app/modules/line/line-form/line-form.component.html
> +            <div class="flex flex-column gap-2" lcControlGroup>
I would suggest putting this in a separate component that implements the `ControlValueAccessor`. This way we can keep the color logic out of the form and make the color selector reusable (maybe later we want to choose colors for rectangles in maps or similar)

2024-10-30 17:40 UTC, dorthrithil commented on client/src/app/modules/line/line-form/line-form.component.ts
> +  protected readonly console = console;
Remove debug var

2024-10-30 17:40 UTC, dorthrithil commented on client/src/app/modules/shared/components/color-square/color-square.component.html
> +<ng-container>
container not needed

2024-10-30 17:40 UTC, dorthrithil commented on client/src/app/utility/misc/color.ts
> +export function highlightColor(color?: string): string | undefined {
For the functions added here, some docstring would be good

2024-11-01 18:48 UTC, BlobbyBob commented on client/src/app/modules/line/line-form/line-form.component.ts
> +  protected readonly console = console;
I removed all console calls, but how thought this sneaks into the code.
I hate it when my IDE is over eager and adds such useless stuff ...

2024-11-01 22:41 UTC, BlobbyBob commented
It's almost finished, but I currently have an error which I did not find a fix yet:
```
NullInjectorError: R3InjectorError(CoreModule)[NgControl -> NgControl]: 
  NullInjectorError: No provider for NgControl!
```

It occurs in `advanced-color-picker.component.ts:65`. However, I don't see any difference to the other components in `shared/forms/controls` where it works.

I think you are a bit more Angular experienced and might be able to find the issue faster than me?

2024-11-02 07:41 UTC, dorthrithil commented
> It's almost finished, but I currently have an error which I did not find a fix yet:
> 
> ```
> NullInjectorError: R3InjectorError(CoreModule)[NgControl -> NgControl]: 
>   NullInjectorError: No provider for NgControl!
> ```
> 
> It occurs in `advanced-color-picker.component.ts:65`. However, I don't see any difference to the other components in `shared/forms/controls` where it works.
> 
> I think you are a bit more Angular experienced and might be able to find the issue faster than me?

Just from a quick look I think this is because of how it's used: `<lc-advanced-color-picker/>`.

Try adding the `formControlName` directive. This way [`NgControl` is provided ](https://github.com/angular/angular/blob/7d0ba0cac85220cbbe4044667a51e5b95512f5d6/packages/forms/src/directives/reactive_directives/form_control_name.ts#L46) and the control knows which control in the form it belongs to.

```
<lc-advanced-color-picker formControlName="color"/>
```

If this isn't the issue, I can have a deeper look.

2024-11-02 12:11 UTC, BlobbyBob commented
> Just from a quick look I think this is because of how it's used: `<lc-advanced-color-picker/>`.

Ah yeah thanks, that fixed it. I was too focused that the issue is with the component itself.

2024-11-02 16:29 UTC, dorthrithil approved these changes

2024-11-02 22:55 UTC, merged