Flexible Hierarchy
LocalCrag/LocalCragApp pull request #492
Opened 2024-11-02 14:04 UTC by BlobbyBob

Implements part of #97 

:sparkles: New instance setting `skippedHierarchicalLayers` with UI
:sparkles: Crags and sectors may have the special slug `_default`
:sparkles: The menu, lists, forms and breadcrumbs hide the hierarchy level when `_default` is found

2024-11-03 21:10 UTC, BlobbyBob commented
This does not completely implement everything mentioned in #97, but the translations are already part of #341 and I will create a new issue for the migrations after this is merged.

2024-11-04 16:52 UTC, dorthrithil requested changes
Had a brief first look. What I currently don't like is, that we now have this situation:

<img width="887" alt="Screenshot 2024-11-04 at 17 46 53" src="https://github.com/user-attachments/assets/7b34e63f-aab8-4bf9-99ac-d9c3884b138a">

We see the ">" in the breadcrumbs without the next element. When we click edit, we edit a hidden element. Not quite sure how to solve this in an easy way. What about hiding "the other way round"?

2024-11-04 16:52 UTC, dorthrithil commented on client/src/app/modules/area/area/area.component.ts
> +        ].filter(menuItem => menuItem.slug != '_default');
Add `_default` as some constant somewhere

2024-11-04 16:52 UTC, dorthrithil commented on client/src/app/modules/core/instance-settings-form/instance-settings-form.component.html
> +          ></p-dropdown>
add a info text / tooltip explaining what this is actually doing

2024-11-04 16:52 UTC, dorthrithil commented on client/src/app/modules/core/instance-settings-form/instance-settings-form.component.html
> +              { value: 0, label: '0 ' + t('skippedHierarchicalLayersItemLabel') },
We could think about labeling this differently. Instead of writing "skipped layers" from 0 to 2, we could instead name the overall label "Hierachy" and then the options "Crag -> Sector -> Area -> Line", "Crag -> Sector -> Line", ...
Internally we can still work with the skipping. But I think re-labeling it makes it clear to the user what happens.

2024-11-04 16:52 UTC, dorthrithil commented on server/src/resources/instance_settings_resources.py
> +                    raise Conflict(ResponseMessage.MIGRATION_IMPOSSIBLE.value)
Would it also be an option to just not show the existing layers anymore? So just keep them but also add the default one. Then we could get rid of this error message and later on offer a function to move e.g. sectors from a now skipped crag to the default crag

2024-11-04 16:52 UTC, dorthrithil commented on client/src/app/modules/crag/crag-list/crag-list.component.ts
> +        this.router.navigate(['topo', '_default', 'sectors']);
Back navigation via browser back arrow doesn't work this way. Can we instead change the routing targets in the first place?

2024-11-05 18:01 UTC, BlobbyBob commented on server/src/resources/instance_settings_resources.py
> +                    raise Conflict(ResponseMessage.MIGRATION_IMPOSSIBLE.value)
My major guideline for this feature has been, that the flexible hierarchy is about content presentation, so I want it to limit the changes to the server to the bare minimum.

If we add another layer of "object visibility", we then have `secret`, `archived` and `skipped` (logically, not as a new property), where we need to handle all combinations and make sure that all internal functions like ranking and search work as expected. I think we should try to avoid this if possible.

This error message is designed to work as a placeholder until we have a feature that is able to migrate more complex scenarios with existing entities into each other.

2024-11-05 18:06 UTC, BlobbyBob commented on client/src/app/modules/crag/crag-list/crag-list.component.ts
> +        this.router.navigate(['topo', '_default', 'sectors']);
Yeah, good catch.
I'll try to adjust the initial links wherever possible, but I like to have this as a fallback solution. I feel, if the project continues to grow, it gets tougher to keep all the configuration possibilities in mind when implementing features and this would be an easy way to mitigate some bugs which are likely to arise.

Of course, `history.back()` should still work reasonably, so I'll look into ways for that.

2024-11-06 18:08 UTC, BlobbyBob commented on client/src/app/modules/core/instance-settings-form/instance-settings-form.component.html
> +              { value: 0, label: '0 ' + t('skippedHierarchicalLayersItemLabel') },
This will get improved even further, when translations suggested in #97 come

2024-11-09 18:43 UTC, dorthrithil requested changes
![Screenshot 2024-11-09 at 18 47 54](https://github.com/user-attachments/assets/34ff018a-6380-43be-aaee-068c0e663a7d)

Fresh db has no hierachy layer setting. Possibly also applies to existing instances?

![Screenshot 2024-11-09 at 18 50 26](https://github.com/user-attachments/assets/fd062310-4d33-4239-91ff-c7899d41a418)

`gymMode` is not sent when offline mode. Only after toggeling the toggle on and off again. 

Some general points:

- When directly accessing `http://localhost:4200/topo` you can still see the region, even with only one hierarchy level. Maybe add a route guard in the router that forwards to the correct view? It can use the instance setting skipped hierarchy levels setting to determine if the view is accessible or not. This would probably make the routing parts in the list components obsolete. Also it would prevent the mismatch of the route and view that is currently possible because of the skipLocationChange (e.g. `/topo/crags` in address bar but area list as view).
- The _default items are still searachable. E.g. you can search for The Tessin Crag if you only have  Region -> Area hierarchy enabled

2024-11-10 07:57 UTC, BlobbyBob commented
> Fresh db has no hierachy layer setting. Possibly also applies to existing instances?

> gymMode is not sent when offline mode. Only after toggeling the toggle on and off again.

Are you sure? When I do `docker compose down -v` and `up` again, both look fine for me.

2024-11-15 21:04 UTC, merged