Custom Grade Scales
LocalCrag/LocalCragApp pull request #520
Opened 2024-11-10 19:58 UTC by BlobbyBob

:sparkles: Adds Grades API
:sparkles: Hierarchy Levels can have default scales set
:sparkles: Adds UI to select scale and defaults for crag/sectors/areas/lines
:sparkles: Adds simple UI to create and manage scales

2024-12-18 18:04 UTC, BlobbyBob commented
@dorthrithil I would be glad, if you would want to try the current state of this one.

The code is not cleaned up yet, and I did not write any tests, but all features should work and I don't expect many bugs.
The known todos are:
- Labels for default scale in create crag/sector/area forms
- Some translations

2024-12-20 22:05 UTC, dorthrithil commented
Hi! Did some first tests, looks nice! Looking forward to add the silly "NB Skala" to my original homecrag Nahetal: https://localcrag-nahetal-kv454.ondigitalocean.app/pages/nb-skala

Some stuff I found:

- Scale form validation is only printed in console "INVALID"
- Grade brackets throw invalid error message:

![Screenshot 2024-12-20 at 22 49 46](https://github.com/user-attachments/assets/437b9e8a-9c8e-4b8d-8c46-25cd553942a0)

- Either Instance settings or region should get a scale setting, otherwise inheriting for a crag is confusing - where does it inherit the scale from? Didn't look in the code yet to figure it out
- Without lines, the skeleton loading animation of the leveled grade distribution is always showing

Nice to have:

- Checkbox setting per instance which line types are available. Many outdoor spots (or at least their topos) either have only routes or only boulders. So it will de-clutter the UI to not show selects that only have one effective option to choose from

Will do some more testing soon, probably after the bracket bug is fixed, so I can create own scales and use them.

2024-12-21 16:56 UTC, BlobbyBob commented
Good catches, I forgot to do a final check in the create mode of the form, the issues should be fixed now.

I renamed the "inherit" option to "not set". Maybe then it might be a bit clearer what it does, i.e., default is taken for hierarchy above or there is just no default if no value is set.

I think the nice to have is already partially covered. The line form only offers line types where a default scale is set. It would be easy to hide if only one option is available.

2025-01-05 15:56 UTC, dorthrithil requested changes
Checked the first 30 files, will continue soon

2025-01-05 15:56 UTC, dorthrithil commented on client/src/app/modules/area/area-form/area-form.component.ts
> +    const scalesPopulated = this.scalesService.getScales().pipe(map(scales => {
This is used in many form components, can be moved in scalesService

2025-01-05 15:56 UTC, dorthrithil commented on client/src/app/modules/ascent/ascent-form/ascent-form.component.ts
> +      next: (scale) => {
No need to use next if you dont need error and complete handlers

2025-01-05 15:56 UTC, dorthrithil commented on client/src/app/modules/ascent/ascent-list/ascent-list.component.ts
> +    // todo hardcoded values
todo

2025-01-05 15:56 UTC, dorthrithil commented on client/src/app/modules/ascent/ascent-list/ascent-list.component.ts
> +  public maxGradeValue = 20;
Dont init with random value

2025-01-05 15:56 UTC, dorthrithil commented on client/src/app/modules/ascent/project-climbed-form-title/project-climbed-form-title.component.html
> +    {{ scalesService.gradeNameByValue(line.type, line.gradeScale, line.gradeValue) | async | translateSpecialGrades }}
Would maybe make sense to create a `lineGrade` pipe, so we can just write `{{.line | lineGrade }}` instead of this line all over the app

2025-01-06 20:04 UTC, dorthrithil requested changes

2025-01-06 20:04 UTC, dorthrithil commented on client/src/app/modules/shared/components/grade-distribution-bar-chart/grade-distribution-bar-chart.component.html
> +    <h6>{{ chartData.lineType }} {{ chartData.gradeScale }}</h6><!-- TODO how should we present these labels? -->
todo - ill write this down on my to-test list, maybe i have a ui idea here

2025-01-06 20:04 UTC, dorthrithil commented on client/src/app/modules/shared/components/leveled-grade-distribution/leveled-grade-distribution.component.ts
> +              labels[i] = `${gradeNameByValueMap[scale.gradeBrackets[i-1] + 1]} - ${gradeNameByValueMap[scale.gradeBrackets[i]]}`; // todo here we assume that grade values are spaced by 1
todo

2025-01-07 17:49 UTC, dorthrithil requested changes
34 files and the testing to go

2025-01-07 17:49 UTC, dorthrithil commented on client/src/app/modules/todo/todo-list/todo-list.component.ts
> +  public maxGradeValue = 20;
same question with the hardcoded default

2025-01-07 17:49 UTC, dorthrithil commented on client/src/app/modules/todo/todo-list/todo-list.component.ts
> +    // todo hardcoded values
todo

2025-01-07 17:49 UTC, dorthrithil commented on client/src/app/services/crud/scales.service.ts
> +      return OPEN_REQUESTS[lineType][name];
Building the cache with ReplaySubjects is a nice way to better integrate with rxjs. Probably not much to change from the current approach

2025-01-08 19:39 UTC, dorthrithil requested changes
Had a look at all the files now. Will now do some more testing

2025-01-08 19:39 UTC, dorthrithil commented on server/src/resources/line_resources.py
> +        # todo add filter options for linetype+gradescale
todo

2025-01-08 19:39 UTC, dorthrithil commented on server/src/resources/sector_resources.py
> +            return NotFound(error), 404
raise

2025-01-08 19:39 UTC, dorthrithil commented on server/src/util/scripts/build_rankings.py
> +                    ascent_value = line.grade_value
Having a single ranking is probably still fine. I think single line type instances will still be the most common case and if there are multiple line types, you'll have to make sure the grade values kind of fit. Separate rankings for line types can easily be implemented as a follow up though

2025-01-08 19:52 UTC, dorthrithil requested changes
The scale setup script should be called once in a migration at the right point in time. Trying to migrate the glees instance ends up in no scales in the instance. It's also not possible to run the setup script before migrating as the relation for scales doesnt exist.

2025-01-11 15:41 UTC, BlobbyBob commented on client/src/app/modules/line/line-list/line-list.component.ts
> +  public maxGradeValue = 9999;
I can try initializing it with `null`. I'm just always unsure how all those PrimeNG components handle such values

2025-01-11 15:49 UTC, BlobbyBob commented on client/src/app/modules/scale/scale-form/scale-form.component.ts
> +    return this.scaleForm.controls.grades as FormArray;
But doesn't the pipe only help in the html part?
I use this method 10 times inside the `.ts` part of the component and would need to inline the type cast every time. I would also not worry about the efficiency of a method return a fixed property and trust the JIT compilers here :wink:

2025-01-13 21:15 UTC, BlobbyBob commented on server/src/resources/line_resources.py
> +        # todo add filter options for linetype+gradescale
was already implemented

2025-01-13 21:22 UTC, BlobbyBob commented on client/src/app/services/crud/scales.service.ts
> +      return OPEN_REQUESTS[lineType][name];
ReplaySubject is similar in some ways yet different and, tbh, I don't really see how it would integrate it with the current caching approach except for getting rid of some `of()` calls, but I don't think this makes the code more understandable or has a noticeable performance impact.

2025-01-15 16:10 UTC, dorthrithil commented on client/src/app/modules/scale/scale-form/scale-form.component.ts
> +    this.scaleForm.disable();
Should work without I think

2025-01-15 16:11 UTC, dorthrithil commented on client/src/app/services/crud/scales.service.ts
> +      return OPEN_REQUESTS[lineType][name];
Yeah, probably also fine like it is. Bit of personal taste, I always like to use the fancy rxjs stuff. :D But it can stay as it is :)

2025-01-15 16:13 UTC, dorthrithil commented on client/src/app/modules/scale/scale-form/scale-form.component.ts
> +    return this.scaleForm.controls.grades as FormArray;
Good points, I guess then it can stay as is :)

2025-01-15 16:16 UTC, dorthrithil commented on client/src/app/modules/line/line-list/line-list.component.ts
> +  public maxGradeValue = 9999;
If they break with null values, we could just not render them until the values are ready

2025-01-15 22:31 UTC, BlobbyBob commented on client/src/app/modules/ascent/project-climbed-form-title/project-climbed-form-title.component.html
> +    {{ scalesService.gradeNameByValue(line.type, line.gradeScale, line.gradeValue) | async | translateSpecialGrades }}
With the current version of LineGradePipe, there is an issue, probably with the asynchronous binding. I'm not really sure how to solve this (in a nice way). Could you maybe take a look?

2025-01-17 14:02 UTC, BlobbyBob commented
> The scale setup script should be called once in a migration at the right point in time. Trying to migrate the glees instance ends up in no scales in the instance. It's also not possible to run the setup script before migrating as the relation for scales doesnt exist.

Is now fixed

2025-01-25 11:54 UTC, dorthrithil commented on client/src/app/modules/ascent/project-climbed-form-title/project-climbed-form-title.component.html
> +    {{ scalesService.gradeNameByValue(line.type, line.gradeScale, line.gradeValue) | async | translateSpecialGrades }}
Setting the pipe `pure=false` fixes the issue:

```
@Pipe({
  name: 'lineGrade',
  pure: false,
})
```

2025-01-25 12:01 UTC, dorthrithil requested changes
![Screenshot 2025-01-25 at 12 56 33](https://github.com/user-attachments/assets/4329257b-76a6-42bf-9a0b-f7365253ab57)
There are a lot of cancelled scale requests. Any idea why this is?

2025-01-25 13:17 UTC, dorthrithil commented on client/src/app/modules/scale/scale-form/scale-form.component.html
> +            <p-message
Hmm, seems like FormArray support is not supported yet. Probably I didn't think of that back in the days when I implemented those directives etc. I'll create an issue for adding support, and then we can update validation in some follow up issue.

2025-01-26 12:40 UTC, BlobbyBob commented
> There are a lot of cancelled scale requests. Any idea why this is?

No, not really. I confirmed that `ScalesService.getScale` reaches the point of calling `this.http.get` exactly once per scale. However, in my dev setup I once even observed two requests fetching the same scale. Maybe its some strange behavior with `HttpClient` in conjunction to multiple subscriptions on an `Observable`?

2025-01-26 12:59 UTC, BlobbyBob commented
I experimented a bit and the amount of requests really depends on the current view. While you barely see (canceled) requests on the line list, there is an extraordinary amount on the ascent list. In fact, there not only many requests being canceled, but also lots of request going out (~10 reqs per scale for me). I find this really strange concerning both log statements
```ts
    console.log(`Sending request ${lineType}/${name}`);
    const req = this.http
      .get(this.api.scales.get(lineType, name))
      .pipe(
        map((x) => (console.log(`Resolving request ${lineType}/${name}`), x)),
```
are run exactly once per scale. This is even more confusing as the only reason I imagined was HttpClient firing multiple times.

2025-01-26 15:55 UTC, dorthrithil requested changes
- When creating a new line, we can currently select wither route or boulder. Traditional is missing, although there is a default scale for it. 
- Also, would it be possible to allow choosing the scale when adding a e.g. boulder if two boulder scales exist in the instance? In Glees we are thinking about adding a "child"-scale and then having mixed areas with children and normal lines. Currently you can only select the default areas scale

2025-01-26 15:55 UTC, dorthrithil commented on client/src/app/modules/scale/scale-form/scale-form.component.ts
> +    this.gradeBracketsControls().push(this.fb.group({name: [], value: [42]}));
Maybe init brackets and grades with null or max + 1 instead of 42?

2025-01-26 15:55 UTC, dorthrithil commented on client/src/app/modules/scale/scale-form/scale-form.component.ts
> +  addBracket() {
Adding many many brackets creates missing color and overflow issues. It would be finde to set a max bracket as a first step and then solve the overflow and colors in separate tickets.

![Screenshot 2025-01-26 at 16 45 47](https://github.com/user-attachments/assets/0def3b29-e0aa-4c75-b39e-edcbb4d64914)
![Screenshot 2025-01-26 at 16 45 53](https://github.com/user-attachments/assets/57242dbc-2421-4fd5-9f97-b294378e02cd)

2025-01-26 17:21 UTC, dorthrithil requested changes

2025-01-26 17:39 UTC, dorthrithil commented
> > There are a lot of cancelled scale requests. Any idea why this is?
> 
> No, not really. I confirmed that `ScalesService.getScale` reaches the point of calling `this.http.get` exactly once per scale. However, in my dev setup I once even observed two requests fetching the same scale. Maybe its some strange behavior with `HttpClient` in conjunction to multiple subscriptions on an `Observable`?

Yes, I also checked that it's only called one time. Hmm.. M

> I experimented a bit and the amount of requests really depends on the current view. While you barely see (canceled) requests on the line list, there is an extraordinary amount on the ascent list. In fact, there not only many requests being canceled, but also lots of request going out (~10 reqs per scale for me). I find this really strange concerning both log statements
> 
> ```ts
>     console.log(`Sending request ${lineType}/${name}`);
>     const req = this.http
>       .get(this.api.scales.get(lineType, name))
>       .pipe(
>         map((x) => (console.log(`Resolving request ${lineType}/${name}`), x)),
> ```
> 
> are run exactly once per scale. This is even more confusing as the only reason I imagined was HttpClient firing multiple times.

Adding the `shareReplay` operator fixes the issue for me. Can you confirm this? Seems like it was some weird interaction between the way `OPEN_REQUESTS` in combination with the cold `HttpClient` observables.

```
    const req = this.http
      .get(this.api.scales.get(lineType, name))
      .pipe(
        map((payload) => Scale.deserializeFull(payload)),
        map((scale) => this.updateCache(scale)),
        map((scale) => {
          delete OPEN_REQUESTS[lineType][name];
          return scale;
        }),
        shareReplay(1)
      );
```

2025-01-28 13:47 UTC, BlobbyBob commented on client/src/app/modules/scale/scale-form/scale-form.component.ts
> +  addBracket() {
As its only a frontend restriction, I've only changed the scaleForm, but not the API. For the wrapping I implemented some wrapping solution and tried to make it as clean as possible, but it is not as clean as it was before.

2025-01-28 13:48 UTC, BlobbyBob commented
`shareReplay(1)` also works for me, good idea.

2025-01-28 21:45 UTC, dorthrithil requested changes
From the last review, maybe the comment got a bit lost:

- When creating a new line, we can currently select wither route or boulder. Traditional is missing, although there is a default scale for it.
- Also, would it be possible to allow choosing the scale when adding a e.g. boulder if two boulder scales exist in the instance? In Glees we are thinking about adding a "child"-scale and then having mixed areas with children and normal lines. Currently you can only select the default areas scale

2025-01-28 21:45 UTC, dorthrithil commented on client/src/app/modules/scale/scale-form/scale-form.component.ts
> +  addBracket() {
This will work for now! I created #567 as a follow-up to handle the restrictions of max 8 brackets.

2025-01-28 21:45 UTC, dorthrithil commented on client/src/app/modules/shared/components/grade-distribution-bar-chart/grade-distribution-bar-chart.component.html
> +    <h6>{{ chartData.lineType }} {{ chartData.gradeScale }}</h6><!-- TODO how should we present these labels? -->
This is still an open todo in the current code, so i unresolved the conversation

2025-01-28 21:45 UTC, dorthrithil commented on client/src/app/modules/todo/todo-list/todo-list.component.html
> +<!--                        {{ scalesService.gradeNameByValue(todo.line.type, todo.line.gradeScale, todo.line.gradeValue) | async | translateSpecialGrades }}-->
Delete commented line

2025-01-29 17:41 UTC, BlobbyBob commented
Ah yeah. I read that but forgot about it as so many new messages appeared in the feed. 

>     * When creating a new line, we can currently select wither route or boulder. Traditional is missing, although there is a default scale for it.
>     * Also, would it be possible to allow choosing the scale when adding a e.g. boulder if two boulder scales exist in the instance? In Glees we are thinking about adding a "child"-scale and then having mixed areas with children and normal lines. Currently you can only select the default areas scale

So, how it currently works is that you can only select line types when you explicitly configured the default scale for the line type for one of the hierarchy levels (if it doesn't, thats a bug). I thought about giving an option to select a scale, but this comes with some downsides. If you, for example, create a child scale for Glees, the scale will also be selectable for Kottenheim and all the other crags. For me, this outweighed the positives. Besides it complicates the already long line form even further.

A more fine-grained scale control per hierarchy level is possible, but requires quite some rework again. Not sure whether we want this in this already huge PR or just move it to a new issue for the future. IMO this is not that urgent.

2025-01-29 19:30 UTC, dorthrithil commented
> So, how it currently works is that you can only select line types when you explicitly configured the default scale for the line type for one of the hierarchy levels (if it doesn't, thats a bug). I thought about giving an option to select a scale, but this comes with some downsides. If you, for example, create a child scale for Glees, the scale will also be selectable for Kottenheim and all the other crags. For me, this outweighed the positives. Besides it complicates the already long line form even further.

> A more fine-grained scale control per hierarchy level is possible, but requires quite some rework again. Not sure whether we want this in this already huge PR or just move it to a new issue for the future. IMO this is not that urgent.

I think it would not be an issue to also have it selectable in Kottenheim. In the end, you as an instance owner decide, whether you want to offer an alternative scale or not. But you're right about the PR already being quite. I'll just create an issue for it to deal with it later.

2025-01-31 16:57 UTC, BlobbyBob commented
I've cleaned up the open stuff and implemented a simple scale change logo. I think its fine for now, but having an open issue for that is certainly good. As an instance admin I would not trust the moderators enough to always adhere to choosing the correct rules :sweat_smile:

2025-02-02 18:38 UTC, dorthrithil approved these changes
Tested the last changes, looks good! The rest we can do in follow-ups as discussed.

2025-02-02 18:53 UTC, merged